blacklist:
  folders:
  - __pycache__
  - .git
  scripts:
  - example
  - telegram
  - concepts
  - slamjam
  - shopnicekicks
  - footpatrol
  - dsm-us
  - dsm-eu
whitelist:
  folders: []
  scripts: []
